### ISSUE TITLE
setup.py?

### ISSUE THREAD

**Issue by AlexJ-StL** [jgravelle/PocketgroqPKE#1]
I am confused a bit. Per the README.md and the directory tree there should be a setup.py file in the root of this repo, but I don't see one. There is a requirements.txt which I can load the dependencies with, so its not a huge deal. The directory tree for the repo that I cloned is below for reference.

Am I missing something?

PocketgroqPKE/
├── demo.py
├── examples/
│   ├── basic_usage.py
│   ├── batch_processing.py
│   ├── custom_prompts.py
│   └── rdf_output.py
├── gardening.pdf
├── geekery.pdf
├── hamsters.pdf
├── LICENSE
├── our_vision_is_therefore_to_extract_procedural.pdf
├── our_vision_is_therefore_to_extract_procedural.ttl
├── pigs.pdf
├── pocketgroq_pke/
│   ├── __init__.py
│   ├── __pycache__/
│   │   ├── __init__.cpython-312.pyc
│   │   ├── extractor.cpython-312.pyc
│   │   └── types.cpython-312.pyc
│   ├── extractor.py
│   ├── templates/
│   │   └── extraction.txt
│   └── types.py
├── README.md
└── requirements.txt

**Comment by jgravelle** [comment]
No, you're right.  I pushed one, but it's untested.

You were right to go the pip install -r requirements.txt route...


-jjg

**Comment by RickySupriyadi** [comment]
https://github.com/jgravelle/PocketgroqPKE/blob/main/setup.py
that is the file

**Comment by AlexJ-StL** [comment]
Awesome!

I appreciate the follow up and, in general, all of the fantastic projects you've been cranking out.

Cheers!
